language: node_js
node_js:
 - "8"
branches:
  only:
    - master
before_deploy:
  - npx semantic-release
deploy:
  on:
    branch: master
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
