language: node_js

node_js:
  - 8

branches:
  only:
    - master

deploy:
  on:
    branch: master
  script:
    - npx semantic-release
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
