language: node_js

node_js:
  - 8

jobs:
  include:

    - stage: npm release
      node_js: 8
      branches:
        only:
          - master
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        github_token: "$GITHUB_TOKEN"
        skip_cleanup: true
      script:
        - npm run sass
        - npx semantic-release
