language: node_js

node_js:
  - 8

branches:
  only:
    - master

jobs:
  include:

    - stage: before deploy
      script:
        - npm run sass
      deploy:
        skip_cleanup: true

    - stage: npm release
      node_js: 8
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        github_token: "$GITHUB_TOKEN"
      script:
        - npx semantic-release
