language: node_js

node_js:
  - 8

branches:
  only:
    - master

notifactions:
  email: false

before_script:
  - npm run sass
  - npm run changelog
  - npm run concat

after_success:
  - npx semantic-release

deploy:
  skip_cleanup: true
